name: Update README.md

on:
  pull_request_target:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{secrets.CONTANE_BOT_TOKEN}}
      - name: Configure Git
        run: |
          git config user.name "contane-bot"
          git config user.email "160241315+contane-bot@users.noreply.github.com"
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm@2.6.1
      - name: Update README.md
        shell: bash
        run: |
          cd charts || exit 1
          for chart in */; do
            # Check if values.yaml has changed
            if git diff --name-only HEAD~1 | grep -q "$chart/values.yaml"; then
              echo "$chart: No values.yaml changes detected"
              continue
            fi
            echo "$chart: values.yaml changes detected"
            echo "Updating README.md for $chart"
            readme-generator --values "$chart/values.yaml" --readme "$chart/README.md"
          done
      - name: Update ArtifactHub change annotations
        shell: bash
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          add_changes_to_chart_yaml() {
            local file_path="Chart.yaml"
            local changes=$1
            if [ ! -f "$file_path" ]; then
              echo "Chart.yaml not found!"
              exit 1
            fi
            chart=$(cat "$file_path")
            # Check if annotations exist
            if ! grep -q "annotations:" <<< "$chart"; then
              chart=$(echo "$chart"$'\n'annotations:)
            fi
            # Check if artifacthub.io/changes annotation exists
            if ! grep -q "artifacthub.io/changes:" <<< "$chart"; then
              chart=$(echo "$chart"$'\n'  artifacthub.io/changes: | sed 's/^/  /')
            fi
            # Append the new changes to the existing ones
            chart=$(echo "$chart"$'\n'"$changes" | sed 's/^/  /')
            echo "$chart" > "$file_path"
          }
          # Parse PR title to create changelog entries
          changes=""
          if [[ $PR_TITLE == *"feat:"* ]]; then
            changes="$changes"$'\n'  - kind: feature
            changes="$changes"$'\n'    description: "${PR_TITLE#*: }"
          elif [[ $PR_TITLE == *"fix:"* ]]; then
            changes="$changes"$'\n'  - kind: bugfix
            changes="$changes"$'\n'    description: "${PR_TITLE#*: }"
          fi
          add_changes_to_chart_yaml "$changes"
      - name: Commit and push changes
        run: |
          cd charts || exit 1
            for chart in */; do
              # Check for changes and commit if necessary
            if git status -s | grep "$chart"; then
              git add "$chart" && git commit -m "docs(${chart%*/}): Update values in README.md" # Remove trailing slash
              git push
            fi
          done
